package nitrogenhotel.ui.panels;

import org.tinylog.Logger;

/** Welcome screen. */
public class WelcomeScreen extends javax.swing.JFrame {

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel backgroundLabel;
  private javax.swing.JPanel backgroundPanel;
  private javax.swing.JProgressBar loadingBar;
  private javax.swing.JLabel loadingLabel;
  private javax.swing.JLabel loadingPercentLabel;
  private javax.swing.JLabel logoLabel;
  private javax.swing.JLabel titleLabel;

  /** Creates new form WelcomeScreen. */
  public WelcomeScreen() {
    initComponents();
    this.setVisible(true);

    try {
      for (int i = 0; i <= 100; i++) {
        Thread.sleep(10);
        loadingPercentLabel.setText(i + "%");

        if (i == 30) {
          loadingLabel.setText("Oiling up the code...");
        }
        if (i == 50) {
          loadingLabel.setText("Almost there...");
        }
        if (i == 60) {
          loadingLabel.setText("Not really...");
        }
        if (i == 85) {
          loadingLabel.setText("Aaaand...");
        }
        if (i == 100) {
          loadingLabel.setText("Done...");
        }
        loadingBar.setValue(i);
      }
    } catch (Exception e) {
      Logger.error("This error should not be received.");
    }
    this.setVisible(false);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    backgroundPanel = new javax.swing.JPanel();
    logoLabel = new javax.swing.JLabel();
    titleLabel = new javax.swing.JLabel();
    loadingLabel = new javax.swing.JLabel();
    loadingPercentLabel = new javax.swing.JLabel();
    loadingBar = new javax.swing.JProgressBar();
    backgroundLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setUndecorated(true);

    backgroundPanel.setPreferredSize(new java.awt.Dimension(900, 500));
    backgroundPanel.setLayout(null);

    logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    logoLabel.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/images/Logo375x375.png"))); // NOI18N
    backgroundPanel.add(logoLabel);
    logoLabel.setBounds(300, 0, 370, 360);

    titleLabel.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/images/titlev2.png"))); // NOI18N
    titleLabel.setText("jLabel1");
    backgroundPanel.add(titleLabel);
    titleLabel.setBounds(130, 380, 700, 100);

    loadingLabel.setText("Loading...");
    backgroundPanel.add(loadingLabel);
    loadingLabel.setBounds(10, 470, 200, 20);

    loadingPercentLabel.setText("0 %");
    backgroundPanel.add(loadingPercentLabel);
    loadingPercentLabel.setBounds(910, 470, 41, 16);

    loadingBar.setBackground(new java.awt.Color(51, 0, 51));
    backgroundPanel.add(loadingBar);
    loadingBar.setBounds(0, 490, 950, 12);

    backgroundLabel.setIcon(
        new javax.swing.ImageIcon(getClass().getResource("/images/gradient900x500.png"))); // NOI18N
    backgroundLabel.setText("jLabel1");
    backgroundPanel.add(backgroundLabel);
    backgroundLabel.setBounds(-3, 0, 950, 500);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(
                backgroundPanel,
                javax.swing.GroupLayout.PREFERRED_SIZE,
                947,
                javax.swing.GroupLayout.PREFERRED_SIZE));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(
                backgroundPanel,
                javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE));

    pack();
    setLocationRelativeTo(null);
  } // </editor-fold>//GEN-END:initComponents
  // End of variables declaration//GEN-END:variables
}
